title:            'Minicomp Wiki'
url:              'minicomp.github.io'
baseurl:          '/wiki'

theme:            just-the-docs
exclude:          [README.md, LICENSE, Gemfile*, Rakefile, vendor]
permalink:        pretty
search_enabled:   false
heading_anchors:  true
source:           src
github:           [metadata]


aux_links:
  'GitHub':
    - 'https://github.com/minicomp/'
  'Wax Demo':
    - 'https://minicomp.github.io/wax/'
  'Ed. Demo':
    - 'https://minicomp.github.io/ed/'

collections:
  sample:
    output: false
    layout: null
    sort_by: test
    metadata:
      source: sample.csv
    images:
      source: sample_images
